# Generated by Django 6.0 on 2025-12-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_payment_payment_url_payment_stripe_price_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_url',
            field=models.URLField(blank=True, max_length=2048, null=True, verbose_name='ссылка на оплату'),
        ),
    ]
